[[redirects]]
  from = "/"
  to = "/at"
  status = 302
  force = true
  conditions = {Country = ["AT"]}

[[redirects]]
  from = "/"
  to = "/at/de"
  status = 302
  force = true
  conditions = {Country = ["AT"], Language = ["de"]}

[[redirects]]
  from = "/"
  to = "/es"
  status = 302
  force = true
  conditions = {Language = ["es"]}

[[redirects]]
  from = "/at/*"
  to = "https://nextjs-redirects-at.netlify.app/at/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "https://nextjs-redirects-us.netlify.app/:splat"
  status = 200


